version: '3'

services:

  eventbus:
    image: rabbitmq:alpine

  datastore:
    image: treehouses/couchdb
    ports:
      - "5984:5984"
    volumes:
      - "./couchdb:/opt/couchdb/data"

  spark:
    image: brewblox/brewblox-devcon-spark:develop
    depends_on:
      - eventbus
      - datastore
    ports:
      - "5000:5000"
    command: >
      --simulation
